lkdfount/msci342project

travvy/src/App.vue
travvy/src/components/Home.vue
travvy/src/components/Landing.vue

Added comments for previous changes including
- improving the aesthetic appeal of the webpage
- making the logo appear on every page and acting as a button to go back to the home page
- cleaning up code

Added comments

---

travvy/src/components/AttractionDetails.vue
travvy/src/components/Landing.vue

Test PR (Saba look at this, review it and comment, merge)

Added AttractionDetails page + Landing page button behaviour

---

travvy-server/src/app.js
travvy-server/src/config/config.js
travvy-server/src/controllers/RecommendController.js
travvy-server/src/models/Attractions.js
travvy-server/src/models/index.js
travvy-server/src/routes.js
travvy/src/components/AttractionsList.vue
travvy/src/components/Home.vue
travvy/src/main.js
travvy/src/router/index.js
travvy/src/services/AttractionsService.js
travvy/src/store/store.js

I cleaned up unnecessary comments in the travvy and travvy server folders to clarify the backend and frontend logic.

Added comments to frontend and backend logic

---

travvy-server/.eslintrc.js
travvy-server/package-lock.json
travvy-server/package.json
travvy-server/src/controllers/DetailsController.js
travvy/package-lock.json
travvy/package.json
travvy/src/components/AttractionDetails.vue
travvy/src/components/AttractionsList.vue
travvy/src/components/Home.vue

Added a details controller file to travvy server, added functionality to Attraction Details page to show various details about each attraction in a dynamic way so that the page changes based on each location, updated the version of eslint in our travvy server folder,

Added a Details Controller file, added functionality to Attraction Details page

---

travvy-server/src/controllers/CitySelectController.js
travvy-server/src/models/Location.js
travvy-server/src/routes.js
travvy/src/components/AttractionDetails.vue
travvy/src/components/AttractionsList.vue
travvy/src/components/Home.vue
travvy/src/services/LocationsService.js

This PR contains the backend for the home page with all new files created (Controller, Service) in order to pull data from the database into the homepage.

Home backend and database pull for locations (dropdown)

---

travvy/src/components/Landing.vue
travvy/src/components/LogIn.vue
travvy/src/router/index.js

- add the front end of the log in page
- make the landing page route to the log in page

Add log in page

---

travvy/src/components/SignUp.vue

- added different styles
- updated the button to match the other pages

Update the style tag to match with the other pages

---

travvy/src/components/SignUp.vue

- Password now hidden instead of showing text when user is registering

Updated the sign up page so password is hidden

---

travvy/src/App.vue
travvy/src/components/SignUp.vue

- Updated App.vue style tag to add code that will add consistent style throughout application
- Removed code from style tag in Signup as it would be redundant code after the additions to App.vue

Updated App.vue style tag 

---

travvy-server/src/controllers/UsersController.js
travvy-server/src/models/Users.js
travvy-server/src/routes.js

added route, usercontroller, and usersjs file. Tested on postman and correctly fetching all user data from database. This can be used to verify username-password combos (login) and add new users to the database (signup). Also modified database so that column is now Instagram_Username instead of Instagram username.

Created User Database Links

---

travvy-server/routes/routes.js
travvy-server/src/controllers/RecommendController.js
travvy/src/components/AttractionsList.vue
travvy/src/components/Home.vue
travvy/src/services/AttractionsService.js
travvy/src/store/store.js

- Now search takes into account group size 
- SQL queries based on group size and location
- Now "No attractions available" appears when no recommended attractions match the users requirements (i.e. if group size is really large) 
TODO 
- Define what error message / style of error should appear if there are no attractions that meet the users requirements

Group size functionality

---

travvy-server/app.js
travvy-server/routes/routes.js

- Deleted code that used UserController - a file made during coding that was not necessary

Deleted code that was not used

---

travvy/package-lock 2.json
travvy/src/components/OnboardingPage.vue
travvy/src/router/index.js

- Added a frontend file for our onboarding page (which the user will be led to after signing up for the first time)
- Created initial fields (age, desired activity type, Instagram handle, etc.)
- Added styling to fields, buttons and card in the background

Onboardingpage frontend

---

travvy-server/app.js
travvy-server/routes/routes.js
travvy-server/src/controllers/AuthenticationController.js
travvy/src/components/LogIn.vue
travvy/src/components/SignUp.vue
travvy/src/services/AuthenticationService.js
travvy/src/store/store.js

- add login to app.js
- add login to routes.js
- add login method to AuthenticationController
- update login component
- add ligin functionality to AuthenticationService
- add user email to the store
- removed "show password" button that was causing problems

Add login functionality

---

travvy-server/routes/routes.js
travvy/src/components/Home.vue
travvy/src/components/Profile.vue

made the profile button functional and added the page where profile will be

Added Profile page

---

travvy/src/App.vue
travvy/src/components/Home.vue
travvy/src/components/LogIn.vue
travvy/src/components/Onboarding.vue
travvy/src/components/SignUp.vue

- Added containers to all pages
- updates styling for all fields by updating the classes for each .vue component and added cohesive styling to app.vue
- commented out onboarding buttons and enforced dropdown, will be figuring out input binding for buttons in the next sprint

updated styling on login/signup + other minor updates

---

travvy/src/App.vue
travvy/src/components/AttractionDetails.vue
travvy/src/components/AttractionsList.vue
travvy/src/components/LogIn.vue
travvy/src/components/Profile.vue
travvy/src/router/index.js

- fixed the profile page (added to the index.js file so when the user routes to /Profile they go to the profile page)
- fixed the UI of the log in page
- added sign out button with correct functionality to the profile page

Sign out and login UI

---

travvy/src/components/LogIn.vue
travvy/src/components/SignUp.vue

- aligned all user input fields
- added required fields
- smaller input box on sign up to make more visually appealing

Signup UI Changes

---

travvy/src/components/LogIn.vue
travvy/src/components/SignUp.vue
travvy/src/services/AuthenticationService.js

The sign up page now handles errors like most sign up pages we're used to on the internet - where you can't have empty fields, etc.
The sign up page throws errors if:
-- any empty fields
-- email is not in proper format
-- password is not at least 6 characters 
-- email is already in the database
Manual testing was completed for each case.

Signup error handling

---

package.json
travvy/package.json
travvy/src/components/AttractionsList.vue
travvy/src/main.js

Google maps implemented into attraction list page
- centers on the city that was searched
- also allows Google Maps features (zoom in and out, street view, move around the map)
- current zoom level of 11 seems optimal (can change this to be more zoomed in or out of city)
- can be further improved to add markers or more details
Unit tests:
- tested all 6 cities currently in the database
- tested entering the minimum and maximum number of travelers (fewer attractions, but no effect on map)
- tested going to page with no city selected (map does not show)
- all unit tests passed

Googlemaps Integration

---

test/unitTests.js
travvy/src/components/Profile.vue

- added unit tests for the log in back end
- unit testing of the log in front end and the sign out features will be done manually
- added comments to sign out feature

Added unit testing for log in

---

travvy/src/App.vue
travvy/src/components/Landing.vue
travvy/src/components/Onboarding.vue

- changed the footer sizing to prevent further overlap on pages
- updated the input field sizing, text and colours on onboarding page
- aligned input fields

ui enhancements

---

test/unitTests.js
travvy-server/src/models/Users.js

- Created unit test to ensure the signup function using authentication controller and using users returned the same response length
- Having the same length of response means all information is being communicated with the database

Signup Unit Testing

---

travvy/src/components/Profile.vue

- created fields for content that we have available in our backend for the user (email, age, activity type, ig handle, etc.)
- added a container for cohesion across pages
- created a list tag for the potential addition of an "edit profile" functionality

Created the main FE components of the profile page

---

test/unitTests.js
travvy-server/app.js
travvy-server/routes/routes.js
travvy-server/src/controllers/AuthenticationController.js
travvy/src/components/Landing.vue
travvy/src/components/Profile.vue
travvy/src/components/SignUp.vue
travvy/src/services/AuthenticationService.js
travvy/src/store/store.js

- added unit testing for getUser function that is used to get user info to populate the profile page
- wrote the getUser route in routes
- created getUser in AuthenticationController to find the user matching the email
- removed the "enter site" button from landing page to force users to log in or sign up
- made the profile populated with the user's information
- made the sign up page log the user into the site by saving their email in the store
- created getUser in the AuthenticationService to return the user's information
- added user information to the store

Profile backend

---

travvy/src/components/Home.vue
travvy/src/components/SelectFile.vue

changed button colours, alignments, added pictures in find next destination section, made headings all same size, and organized overall layout

Home Page UI enhancements

---

travvy/src/App.vue
travvy/src/components/AttractionsList.vue
travvy/src/components/Home.vue

- Added separator lines in order to organize content
- updated the footer once more to ensure that it is only visible if the user scrolls to the bottom of the page
- separated location suggestion buttons and changed colours and font for a more pleasant user experience 
- made the profile and home page buttons on the attractions page more consistent

Made enhancements on the attractions list page 

---

travvy/src/components/AttractionsList.vue

Got 3 reviews from tripadvisor for each city, added logic so it appears for correct city. Tested all cities and reviews appear correctly. Also switched layout so map is before reviews. Made minor UI changes.

Added Reviews for each city

---

travvy/src/components/SignUp.vue

- Added "* = reuqired field" at top of the page to ensure users knew what was meant by the * beside each of the fields
- Added this clarification based on feedback from other group members

Added information about required field

---

travvy-server/routes/routes.js
travvy-server/src/controllers/AuthenticationController.js
travvy-server/src/controllers/RecommendController.js
travvy-server/src/models/Users.js
travvy/src/components/Onboarding.vue
travvy/src/services/AuthenticationService.js

- Users table edited and activity_id column added
- activity_id populated for each user based on their preferred activity type specified in onboarding
- Attractions shown after entering location now appear only if they fit the user's activity type
- Adds the personalized experience of Travvy
Unit testing done - https://github.com/lkdfount/msci342project/pull/78

Attractions appear based on user's specified preferred activity type

---

travvy/src/components/Home.vue

- Added required star labels for user input of parameters 
- Errors will now appear if user did not input a field

Added error handling of required fields in search

---

travvy/src/components/Onboarding.vue

- Deleted old code in onboarding file that was commented out
- Was not preventing any code from working - just did not need to be in the file

Cleaned up old comments in onboarding.vue

---

test/unitTests.js

This unit test ensures that a user can still sign up and the authentication controller is running properly after adding activity_id to users table. 
Test constants:
name = Test1
email = testemail1@outlook.com
password = Helloworld1
Assert:
length of response is equal to the length of information about user.

Added Unit Test for Authentication Controller

---

test/unitTests.js
travvy/src/components/Profile.vue

- Now if user updates their preference / interest the associated activity id will be populated in the database 
- Since update fields are not required on the profile page, I added handling if the user does not input any values into the text fields if they do not want to update them. When I was working on this, when I did not fully fill out the form it would not actually update in the database even though it would pass successfully in the front end. Now this is not an issue.
- Similar strategy to this PR - https://github.com/lkdfount/msci342project/pull/77
- Created a change to a past unit test

Added insert of updated preferences in onboarding

---

travvy/src/components/AttractionDetails.vue
travvy/src/components/AttractionsList.vue

Made some UI changes (font sizes, added container, picture size, etc)

UI Changes to Attractions Details Page

---

travvy/src/components/Home.vue

- Updated the sizing for destination dropdown, dates & traveller input value
- Updated the UI components in order to align with the rest of the input fields throughout the app

Made UI updates to Home Screen

---

travvy/src/components/AttractionsList.vue
travvy/src/components/Home.vue
travvy/src/components/Onboarding.vue
travvy/src/components/Profile.vue
travvy/src/components/SelectFile.vue

- Added error messaging to onboarding flow which is consistent to other pages in the app
- Added user specific metadata to each file upload so that the upload is marked with the users email on Firebase
- Added a "View Travel Documents" button onto the Profile page where user can view their uploaded documents
- Attempted to add dynamic User Name within a greeting message on Home page, will update in future PR

Updated error messaging on Onboarding, Added user specific meta data to file upload, Added "View Travel Documents" feature
